
# @author [Majid Farr Amini]
# @email [majid.f.amini@gmail.com]
# @create date 2023-03-15
# @desc [Automation - Backup Cisco Router or Switch]
---
- name: Backup running config and save it on timestamp folder
  hosts: all
  gather_facts: false

  tasks:

    - name: Accespt ansible net hostname
      ios_facts:
        gather_subset: all

    - name: Get current date
      local_action: command date +%Y-%b-%d
      register: date

    - name: Get current time
      local_action: command date +%H:%M
      register: time

    - name: Get running-config and save it
      ios_config:
       backup: yes
       backup_options:
         #ansible_host = getting device IP, ansible_net_hostname = getting device hostname
         filename: "{{ ansible_net_hostname }}_{{ ansible_host }}.txt"
         #Please change /home/hawar/Desktop to your direcotry
         #Every time create a new directory under named date and time
         dir_path: /etc/ansible/backups/{{ date.stdout }}

    - name: Tasks done
      debug: msg="All tasks has been done on {{ date.stdout }} at {{ time.stdout }}."

#End of codes
